/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from "./Role";

export interface RegistrationRequest {
  email: string;
  firstname: string;
  lastname: string;
  password: string;
  role: Role;
  

}
